### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by jasoncorbett** [cisco-open-source/qtwebdriver#13]
I've tried following the instructions in the build page, both with the builtin version of QT in ubuntu, and a different version (I need version 4.7.4).  I've tried various options in the wd.gypi but the build always fails at one point:

```
CXX(target) Default/obj.target/WebDriver_core/src/third_party/pugixml/pugixml.o
  AR(target) Default/obj.target/libWebDriver_core.a
  COPY Default/libWebDriver_core.a
  ACTION wd_ext_qt_gyp_WebDriver_extension_qt_base_target_input_dir  Default/obj.target/WebDriver_extension_qt_base/geni
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_0  inc/extension_qt/moc_q_view_runner.cc
Traceback (most recent call last):
  File "do_if_modified.py", line 25, in <module>
     p = sp.Popen([action_process, input_file , "-o", output_file], stdin=sp.PIPE, stdout=sp.PIPE)
   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
     errread, errwrite)
   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
     raise child_exception
 OSError: [Errno 2] No such file or directory
 make: *** [inc/extension_qt/moc_q_view_runner.cc] Error 1
```

If I've missed a step please let me know.  Also I was wondering if there is a mailing list or other group to discuss this project?

**Comment by hekra01** [comment]
Hi Jason,
- Please make sure you use a qt version >= 4.8.2
- then for you specific issue try by modifying `do_if_modified.py` like this

``` python
  p = sp.Popen([action_process, input_file , "-o", output_file], stdin=sp.PIPE, stdout=sp.PIPE, shell=True)
```

Guess it is a python of shell related issue, bu tI did not encounter it

> Also I was wondering if there is a mailing list or other group to discuss this project?

Not yet, but this is a good idea. I'll look into it.

**Comment by mass85** [comment]
I had exactly the same problem. Once I modified do_if_modified.py I got error:

```
CXX(target) Default/obj.target/WebDriver_core/src/webdriver/webdriver_version.o
  AR(target) Default/obj.target/libWebDriver_core.a
  COPY Default/libWebDriver_core.a
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_0 inc/extension_qt/moc_q_view_runner.cc
/home/marcin/Kelvatek/qtwebdriver/inc/extension_qt/q_view_runner.h: 1: /home/marcin/Kelvatek/qtwebdriver/inc/extension_qt/q_view_runner.h: /usr/lib/qt4/bin/moc: not found
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_1 src/webdriver/extension_qt/moc_q_event_filter.cc
/home/marcin/Kelvatek/qtwebdriver/src/webdriver/extension_qt/q_event_filter.h: 1: /home/marcin/Kelvatek/qtwebdriver/src/webdriver/extension_qt/q_event_filter.h: /usr/lib/qt4/bin/moc: not found
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_2 inc/extension_qt/moc_vncclient.cc
/home/marcin/Kelvatek/qtwebdriver/inc/extension_qt/vncclient.h: 1: /home/marcin/Kelvatek/qtwebdriver/inc/extension_qt/vncclient.h: /usr/lib/qt4/bin/moc: not found
  CXX(target) Default/obj.target/WebDriver_extension_qt_base/src/webdriver/extension_qt/q_content_type_resolver.o
In file included from ../../../src/webdriver/extension_qt/q_content_type_resolver.cc:20:0:
../../../src/webdriver/extension_qt/q_content_type_resolver.h:24:43: fatal error: QtNetwork/QNetworkAccessManager: No such file or directory
compilation terminated.
WebDriver_extension_qt_base.target.mk:142: recipe for target 'Default/obj.target/WebDriver_extension_qt_base/src/webdriver/extension_qt/q_content_type_resolver.o' failed
make: *** [Default/obj.target/WebDriver_extension_qt_base/src/webdriver/extension_qt/q_content_type_resolver.o] Error 1
```

It helped me realize that I have not configured proper paths in wd.gypi: QT_BIN_PATH, QT_INC_PATH and QT_LIB_PATH. Unfortunately fixing that issue gave exactly the same error. So I had a look at all files that included wd.gypi and thought that maybe my values get overwritten with wd_common.gypi. I changed order of files inclusion to:

```
'includes': [
    'wd_common.gypi',
    'wd.gypi',
  ]
```

Now I get a different error:

```
  CXX(target) Default/obj.target/WebDriver_extension_qt_base/src/webdriver/extension_qt/uinput_event_dispatcher.o
  AR(target) Default/obj.target/libWebDriver_extension_qt_base.a
ar: Default/obj.target/WebDriver_extension_qt_base/geni/moc_q_view_runner.o: No such file or directory
WebDriver_extension_qt_base.target.mk:177: recipe for target 'Default/obj.target/libWebDriver_extension_qt_base.a' failed
make: *** [Default/obj.target/libWebDriver_extension_qt_base.a] Error 1
```

In fact directory out/desktop/release/Default/obj.target/WebDriver_extension_qt_base/geni/ is empty...

When I repeat the build command I get something that might be helpful:

```
marcin@marcin-HP-ProBook-6570b:~/Kelvatek/qtwebdriver$ ./build.sh ./out
  CXX(target) Default/obj.target/WebDriver_core/src/webdriver/webdriver_version.o
  AR(target) Default/obj.target/libWebDriver_core.a
  COPY Default/libWebDriver_core.a
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_0 inc/extension_qt/moc_q_view_runner.cc
standard input:0: Note: No relevant classes found. No output generated.
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_1 src/webdriver/extension_qt/moc_q_event_filter.cc
standard input:0: Note: No relevant classes found. No output generated.
  RULE wd_ext_qt_gyp_WebDriver_extension_qt_base_target_generate_moc_2 inc/extension_qt/moc_vncclient.cc
standard input:0: Note: No relevant classes found. No output generated.
  AR(target) Default/obj.target/libWebDriver_extension_qt_base.a
ar: Default/obj.target/WebDriver_extension_qt_base/geni/moc_q_view_runner.o: No such file or directory
WebDriver_extension_qt_base.target.mk:177: recipe for target 'Default/obj.target/libWebDriver_extension_qt_base.a' failed
make: *** [Default/obj.target/libWebDriver_extension_qt_base.a] Error 1
```

**Comment by hekra01** [comment]
Hi @mass85 

> and thought that maybe my values get overwritten with wd_common.gyp

Please make sure ther is no `%` left in you wd.gypi. It should look like this

```
{
  'variables': {
    'QT5': '1',
    'WD_CONFIG_QWIDGET_BASE': '1',
    'WD_CONFIG_WEBKIT': '1',
    'WD_CONFIG_QUICK': '1',
    'WD_BUILD_MONGOOSE': '1',
    'WD_CONFIG_PLAYER': '1',
    'WD_CONFIG_ONE_KEYRELEASE': '0',
    'QT_INC_PATH': '/home/hekra01/Qt5.2.1/5.2.1/gcc_64/include',
    'QT_BIN_PATH': '/home/hekra01/Qt5.2.1/5.2.1/gcc_64/bin',
    'QT_LIB_PATH': '/home/hekra01/Qt5.2.1/5.2.1/gcc_64/lib'
  },
}
```

You error message
`
Default/obj.target/WebDriver_extension_qt_base/geni/moc_q_view_runner.o: No such file or directory
`

is a consequent of your firs error
`
/src/webdriver/extension_qt/q_event_filter.h: /usr/lib/qt4/bin/moc: not found
`
Please check you Qt install. Also you should use Qt >= 4.8.2

**Comment by mass85** [comment]
> You error message
> Default/obj.target/WebDriver_extension_qt_base/geni/moc_q_view_runner.o: No such file or directory
> 
> is a consequent of your firs error
> /src/webdriver/extension_qt/q_event_filter.h: /usr/lib/qt4/bin/moc: not found
> Please check you Qt install. Also you should use Qt >= 4.8.2

Not really. As I mentioned before I have the paths already fixed and no longer get error about moc not found.

> Please make sure ther is no % left in you wd.gypi.

This did the job and I was able to revert my changes in .gyp files.

My wd.gypi looks like this:

```
{
  'variables': {
    'QT5': '0',
    'WD_CONFIG_QWIDGET_BASE': '1',
    'WD_CONFIG_WEBKIT': '1',
    'WD_CONFIG_QUICK': '1',
    'WD_BUILD_MONGOOSE': '0',
    'WD_CONFIG_PLAYER': '1',
    'WD_CONFIG_ONE_KEYRELEASE': '0',

    'QT_BIN_PATH': '/usr/lib/x86_64-linux-gnu/qt4/bin/',
    'QT_INC_PATH': '/usr/include/qt4',
    'QT_LIB_PATH': '/usr/lib/x86_64-linux-gnu/qt4/lib',
    'MONGOOSE_INC_PATH': 'src/third_party/mongoose',

    'conditions': [

      [ 'OS == "android"', {
        'ANDROID_INC': '<!(/bin/echo -n $ANDROID_NDK_ROOT)/sources/cxx-stl/gnu-libstdc++/4.7/libs/<!(/bin/echo -n $ANDROID_LIB_ARCH)/include',
        'ANDROID_LIB_INC': '<!(/bin/echo -n $ANDROID_NDK_ROOT)/sources/cxx-stl/gnu-libstdc++/4.7/include',
        'ANDROID_PLATFORM_INC': '<!(/bin/echo -n $ANDROID_NDK_ROOT)/platforms/android-9/arch-<!(/bin/echo -n $ANDROID_ARCH)/usr/include',
        'ANDROID_LIB': '<!(/bin/echo -n $ANDROID_NDK_ROOT)/sources/cxx-stl/gnu-libstdc++/4.7/libs/<!(/bin/echo -n $ANDROID_LIB_ARCH)',
      } ],

    ],
  },
}
```

The Qt paths are correct, they even match with what QtCreator tells me:

```

Name:
Qt 4.8.6 (System)
ABI:
x86-linux-generic-elf-64bit
Source:
/usr
mkspec:
linux-g++-64
qmake:
/usr/bin/qmake-qt4
Version:
4.8.6
QMAKE_VERSION
2.01a
QT_HOST_BINS
/usr/lib/x86_64-linux-gnu/qt4/bin
QT_HOST_DATA
/usr/share/qt4
QT_HOST_PREFIX
/usr
QT_INSTALL_BINS
/usr/lib/x86_64-linux-gnu/qt4/bin
QT_INSTALL_CONFIGURATION
/etc/xdg
QT_INSTALL_DATA
/usr/share/qt4
QT_INSTALL_DEMOS
/usr/lib/qt4/demos
QT_INSTALL_DOCS
/usr/share/qt4/doc
QT_INSTALL_EXAMPLES
/usr/lib/qt4/examples
QT_INSTALL_HEADERS
/usr/include/qt4
QT_INSTALL_IMPORTS
/usr/lib/x86_64-linux-gnu/qt4/imports
QT_INSTALL_LIBS
/usr/lib/x86_64-linux-gnu
QT_INSTALL_PLUGINS
/usr/lib/x86_64-linux-gnu/qt4/plugins
QT_INSTALL_PREFIX
/usr
QT_INSTALL_TRANSLATIONS
/usr/share/qt4/translations
QT_VERSION
4.8.6
```

As you can see I use Qt 4.8.6.

**Comment by hekra01** [comment]
@jasoncorbett
you can post to this mailing list qtwebdriver-users@external.cisco.com
Also, did `shell=True`fix your issue?

@mass85
- I download and build Qt-4.8.6 from source
- I rebuild wd with qt-4.8.6
  [WebDriver.zip](https://github.com/cisco-open-source/qtwebdriver/files/67923/WebDriver.zip)
- my wd.gypi

```
{
  'variables': {
    'QT5': '0',
    'WD_CONFIG_QWIDGET_BASE': '1',
    'WD_CONFIG_WEBKIT': '1',
    'WD_CONFIG_QUICK': '1',
    'WD_BUILD_MONGOOSE': '1',
    'WD_CONFIG_PLAYER': '0',
    'WD_CONFIG_ONE_KEYRELEASE': '0',
    'QT_INC_PATH': '/home/hekra01/qt-4.8.6/include',
    'QT_BIN_PATH': '/home/hekra01/qt-4.8.6/bin',
    'QT_LIB_PATH': '/home/hekra01/qt-4.8.6/lib'
  },
}
```
- WD_CONFIG_PLAYER should be 0 for Qt4
- make sure your path looks in you Qt install first

```
export PATH=/home/hekra01/qt-4.8.6/bin:$PATH
```
- then build

**Comment by mass85** [comment]
Unfortunately after applying above remarks I still get the same error. However I have not built Qt from scratch using some custom or default config (as you probably did), but simply installed it from Ubuntu repositories. Anyway the problem I am observing looks like a bug in build system, but I do no know gyp at all, so fixing it on my own might be hard.

**Comment by hekra01** [comment]
@mass85,
I installed Qt4 from repo

```
$ python -V
Python 2.7.6

$ uname -a
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

$ sudo apt-get install qt4-dev-tools libqt4-dev libqt4-core libqt4-gui

$ /usr/lib/x86_64-linux-gnu/qt4/bin/moc -v
Qt Meta Object Compiler version 63 (Qt 4.8.6)

$ cat wd.gypi
{
  'variables': {
    'QT5': '0',
    'WD_CONFIG_QWIDGET_BASE': '1',
    'WD_CONFIG_WEBKIT': '1',
    'WD_CONFIG_QUICK': '1',
    'WD_BUILD_MONGOOSE': '1',
    'WD_CONFIG_PLAYER': '0',
    'WD_CONFIG_ONE_KEYRELEASE': '0',
    'QT_INC_PATH': '/usr/include/qt4',
    'QT_BIN_PATH': '/usr/lib/x86_64-linux-gnu/qt4/bin',
    'QT_LIB_PATH': '/usr/lib/x86_64-linux-gnu/'
  },
}
```

Observe my `QT_LIB_PATH` is `/usr/lib/x86_64-linux-gnu/`, 
Yours is `/usr/lib/x86_64-linux-gnu/qt4/lib`
Then I rebuild

```
$ rm -rf ./out # Make sure you remove build output before rebuild
$ ./build.sh
```

I manage to build WD. I attach the bin [WebDriver.zip](https://github.com/cisco-open-source/qtwebdriver/files/68764/WebDriver.zip)

**Comment by hekra01** [comment]
Previous answser should fix this. Ping back if other issues.
